---
# - set_fact:
#     real_ansible_host: "{{ ansible_host }}"

- name: 'Update APT package cache'
  apt:
    update_cache: yes

- name: 'Upgrade APT to the lastest packages'
  apt:
    upgrade: dist

- name: Run a script with arguments (free form)
  shell: 
    cmd: echo "hello" > testing.txt
    chdir: /home/pi
    creates: /home/pi/testing.txt

- name: install zabbix deb
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/raspbian/pool/main/z/zabbix-release/zabbix-release_5.0-1+buster_all.deb

